version: '3'
services:
  nginx:
    container_name: magento2-nginx
    image: eterlabs/nginx-php74
    volumes:
      - ./code:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/php.ini:/etc/php/7.4/fpm/php.ini
      - ./var/:/var/log/nginx
      - ./config/auth.json:/root/.config/composer/auth.json
    ports:
      - 8070:80
    extra_hosts:
      - "host.docker.local:host-gateway"
    links:
      - elasticsearch
      - mariadb

  mariadb:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento
      MYSQL_PASSWORD: magentopass

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: magento2-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200